/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Button } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&family=Concert+One&family=Playwrite+IT+Moderna:wght@100..400&family=Pochaevsk&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Germania+One&family=Lilita+One&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
        </link>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bree+Serif&family=Concert+One&family=Playwrite+IT+Moderna:wght@100..400&family=Pochaevsk&display=swap"
          rel="stylesheet">
        </link>
      </head>
      <body

      >
        <AppRouterCacheProvider>

          <header className="bg-white shadow-md sticky top-0 z-10">
            <div className="container mx-auto flex justify-between items-center px-6 py-4">
              <h1 className="text-2xl  tracking-wide">
                AI Wellness Coach
              </h1>
              <nav className="flex items-center space-x-6">
              <Button variant="contained">
                <Link
                  href="/signup"
                >
                  Sign Up
                </Link>

              </Button>
              <Button variant="outlined">

                <Link
                  href="/login"
                >
                  Log In
                </Link>
              </Button>


              </nav>
            </div>
          </header>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
